### ISSUE TITLE
Bug in debug object bad hook

### ISSUE THREAD

**Issue by greenozon** [Ahora57/AmogusPlugin#3]
Just built the app and ran it in console...  (no debugger, no hiders, etc)

![image](https://user-images.githubusercontent.com/765343/185978354-500d5708-a35e-4ca6-9729-dcbac1c4047e.png)

**Comment by Ahora57** [comment]
> Just built the app and ran it in console... (no debugger, no hiders, etc)
> 
> ![image](https://user-images.githubusercontent.com/765343/185978354-500d5708-a35e-4ca6-9729-dcbac1c4047e.png)

Write  me on Discord/Telegram as everything is working fine for me (I don't want to leave a lot of dirt in this request)
1)x32/x64 app?
2)Сompiling with LLVM?
P.S. I will try to help as much as I can, but there is no guarantee that it will work out(I have no desire to update this project).

**Comment by greenozon** [comment]
OK, thanks for promt reply
1 - x64
2 - using MSVC2019 latest (16.11.18)
llvm is a separate compiler, do you mean there are some ways to integrate it with msvc and produce win binary?...
never used that mode, but why  exactly llvm you need?
are you using some C++ ultra modern features or what is the reason for that

I dont believe that app in C++ will work in compiler and fail in anohter one (in runtime, not at compile time)

where could I find your dc/tg

**Comment by Ahora57** [comment]
> 

1)I use LLVM because it compiles code quickly multiple times + i can use inline asm x64.
2)[Check my readme](https://github.com/Ahora57/Ahora57)

**Comment by greenozon** [comment]
thanks
but still, I did not find any "asm" directive in this repo, also speed of compilation is irrelevant to the runtime bug as shown on the picture above...

**Comment by Ahora57** [comment]
> msvc compiler

We are starting a dispute MSVC compiler vs LLVM compiler.
I will not continue any dialogues on a similar topic, for logical reasons.

**Comment by greenozon** [comment]
it's not dispute, its discussion about bug in the code...
OK, I"ll try to debug the bug myself

**Comment by Ahora57** [comment]
Since I can't replicate the bug and haven't been contacted, I'm closing this issue.
